const myData = {
    "prices": [{
        "resourceCode": "PAX",
        "price": 0,
        "ticketType": "BST",
        "type": "A",
        "available": true,
        "yieldClass": "A",
        "capacity": 261,
        "intervalValue": 0,
        "resourceType": 1
    }, {
        "resourceCode": "PAX",
        "price": 0,
        "ticketType": "DD0",
        "type": "A",
        "available": true,
        "yieldClass": "A",
        "capacity": 261,
        "intervalValue": 0,
        "resourceType": 1
    }, {
        "resourceCode": "PAX",
        "price": 30,
        "ticketType": "STD",
        "type": "A",
        "available": true,
        "yieldClass": "A",
        "capacity": 261,
        "intervalValue": 0,
        "resourceType": 1
    }, {
        "resourceCode": "PAX",
        "price": 27,
        "ticketType": "VCN",
        "type": "A",
        "available": true,
        "yieldClass": "A",
        "capacity": 261,
        "intervalValue": 0,
        "resourceType": 1
    }, {
        "resourceCode": "NEXEC",
        "price": 30,
        "ticketType": "BST",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NEXEC",
        "price": 30,
        "ticketType": "BST",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NEXEC",
        "price": 30,
        "ticketType": "BST",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NEXEC",
        "price": 0,
        "ticketType": "DD0",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NEXEC",
        "price": 0,
        "ticketType": "DD0",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NEXEC",
        "price": 0,
        "ticketType": "OOO",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NEXEC",
        "price": 0,
        "ticketType": "SOB",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NEXEC",
        "price": 142,
        "ticketType": "STD",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NEXEC",
        "price": 142,
        "ticketType": "STD",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NEXEC",
        "price": 142,
        "ticketType": "STD",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NEXEC",
        "price": 142,
        "ticketType": "VCN",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NEXEC",
        "price": 142,
        "ticketType": "VCN",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NEXEC",
        "price": 142,
        "ticketType": "VCN",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI2",
        "price": 0,
        "ticketType": "BST",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI2",
        "price": 0,
        "ticketType": "BST",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI2",
        "price": 0,
        "ticketType": "BST",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI2",
        "price": 0,
        "ticketType": "DD0",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI2",
        "price": 0,
        "ticketType": "DD0",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI2",
        "price": 0,
        "ticketType": "OOO",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI2",
        "price": 0,
        "ticketType": "SOB",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI2",
        "price": 77,
        "ticketType": "STD",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI2",
        "price": 77,
        "ticketType": "STD",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI2",
        "price": 77,
        "ticketType": "STD",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI2",
        "price": 77,
        "ticketType": "VCN",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI2",
        "price": 77,
        "ticketType": "VCN",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI2",
        "price": 77,
        "ticketType": "VCN",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI4",
        "price": 0,
        "ticketType": "BST",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI4",
        "price": 0,
        "ticketType": "BST",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI4",
        "price": 0,
        "ticketType": "BST",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI4",
        "price": 0,
        "ticketType": "DD0",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI4",
        "price": 0,
        "ticketType": "DD0",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI4",
        "price": 0,
        "ticketType": "OOO",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI4",
        "price": 0,
        "ticketType": "SOB",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI4",
        "price": 109,
        "ticketType": "STD",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI4",
        "price": 109,
        "ticketType": "STD",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI4",
        "price": 109,
        "ticketType": "STD",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI4",
        "price": 109,
        "ticketType": "VCN",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI4",
        "price": 109,
        "ticketType": "VCN",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI4",
        "price": 109,
        "ticketType": "VCN",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI4S",
        "price": 0,
        "ticketType": "BST",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI4S",
        "price": 0,
        "ticketType": "BST",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI4S",
        "price": 0,
        "ticketType": "BST",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI4S",
        "price": 0,
        "ticketType": "DD0",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI4S",
        "price": 0,
        "ticketType": "DD0",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI4S",
        "price": 0,
        "ticketType": "OOO",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI4S",
        "price": 0,
        "ticketType": "SOB",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI4S",
        "price": 109,
        "ticketType": "STD",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI4S",
        "price": 109,
        "ticketType": "STD",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI4S",
        "price": 109,
        "ticketType": "STD",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI4S",
        "price": 109,
        "ticketType": "VCN",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI4S",
        "price": 109,
        "ticketType": "VCN",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NI4S",
        "price": 109,
        "ticketType": "VCN",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NID",
        "price": 0,
        "ticketType": "BST",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NID",
        "price": 0,
        "ticketType": "BST",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NID",
        "price": 0,
        "ticketType": "BST",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NID",
        "price": 0,
        "ticketType": "DD0",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NID",
        "price": 0,
        "ticketType": "DD0",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NID",
        "price": 0,
        "ticketType": "OOO",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NID",
        "price": 0,
        "ticketType": "SOB",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NID",
        "price": 109,
        "ticketType": "STD",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NID",
        "price": 109,
        "ticketType": "STD",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NID",
        "price": 109,
        "ticketType": "STD",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NID",
        "price": 109,
        "ticketType": "VCN",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NID",
        "price": 109,
        "ticketType": "VCN",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NID",
        "price": 109,
        "ticketType": "VCN",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NIDPH",
        "price": 16,
        "ticketType": "BST",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NIDPH",
        "price": 0,
        "ticketType": "DD0",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NIDPH",
        "price": 0,
        "ticketType": "OOO",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NIDPH",
        "price": 0,
        "ticketType": "SOB",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NIDPH",
        "price": 119,
        "ticketType": "STD",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NIDPH",
        "price": 119,
        "ticketType": "STD",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NIDPH",
        "price": 119,
        "ticketType": "STD",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NIDPH",
        "price": 119,
        "ticketType": "VCN",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NIDPH",
        "price": 119,
        "ticketType": "VCN",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NIDPH",
        "price": 119,
        "ticketType": "VCN",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NIDX",
        "price": 0,
        "ticketType": "BST",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NIDX",
        "price": 0,
        "ticketType": "BST",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NIDX",
        "price": 0,
        "ticketType": "BST",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NIDX",
        "price": 0,
        "ticketType": "DD0",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NIDX",
        "price": 0,
        "ticketType": "OOO",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NIDX",
        "price": 0,
        "ticketType": "SOB",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NIDX",
        "price": 109,
        "ticketType": "STD",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NIDX",
        "price": 109,
        "ticketType": "STD",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NIDX",
        "price": 109,
        "ticketType": "STD",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NIDX",
        "price": 109,
        "ticketType": "VCN",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NIDX",
        "price": 109,
        "ticketType": "VCN",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NIDX",
        "price": 109,
        "ticketType": "VCN",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NO2",
        "price": 0,
        "ticketType": "BST",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NO2",
        "price": 0,
        "ticketType": "BST",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NO2",
        "price": 0,
        "ticketType": "BST",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NO2",
        "price": 0,
        "ticketType": "DD0",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NO2",
        "price": 0,
        "ticketType": "DD0",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NO2",
        "price": 0,
        "ticketType": "OOO",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NO2",
        "price": 0,
        "ticketType": "SOB",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NO2",
        "price": 112,
        "ticketType": "STD",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NO2",
        "price": 112,
        "ticketType": "STD",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NO2",
        "price": 112,
        "ticketType": "STD",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NO2",
        "price": 112,
        "ticketType": "VCN",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NO2",
        "price": 112,
        "ticketType": "VCN",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NO2",
        "price": 112,
        "ticketType": "VCN",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NO3",
        "price": 0,
        "ticketType": "BST",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NO3",
        "price": 0,
        "ticketType": "BST",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NO3",
        "price": 0,
        "ticketType": "BST",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NO3",
        "price": 0,
        "ticketType": "DD0",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NO3",
        "price": 0,
        "ticketType": "DD0",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NO3",
        "price": 0,
        "ticketType": "OOO",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NO3",
        "price": 0,
        "ticketType": "SOB",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NO3",
        "price": 112,
        "ticketType": "STD",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NO3",
        "price": 112,
        "ticketType": "STD",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NO3",
        "price": 112,
        "ticketType": "STD",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NO3",
        "price": 112,
        "ticketType": "VCN",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NO3",
        "price": 112,
        "ticketType": "VCN",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NO3",
        "price": 112,
        "ticketType": "VCN",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETI2",
        "price": 0,
        "ticketType": "OOO",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETI2",
        "price": 0,
        "ticketType": "SOB",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETI2",
        "price": 77,
        "ticketType": "STD",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETI2",
        "price": 77,
        "ticketType": "STD",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETI2",
        "price": 77,
        "ticketType": "STD",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETI4",
        "price": 0,
        "ticketType": "BST",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETI4",
        "price": 0,
        "ticketType": "BST",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETI4",
        "price": 0,
        "ticketType": "BST",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETI4",
        "price": 0,
        "ticketType": "DD0",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETI4",
        "price": 0,
        "ticketType": "OOO",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETI4",
        "price": 0,
        "ticketType": "SOB",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETI4",
        "price": 109,
        "ticketType": "STD",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETI4",
        "price": 109,
        "ticketType": "STD",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETI4",
        "price": 109,
        "ticketType": "STD",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETI4",
        "price": 109,
        "ticketType": "VCN",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETI4",
        "price": 109,
        "ticketType": "VCN",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETI4",
        "price": 109,
        "ticketType": "VCN",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETO2",
        "price": 0,
        "ticketType": "BST",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETO2",
        "price": 0,
        "ticketType": "BST",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETO2",
        "price": 0,
        "ticketType": "BST",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETO2",
        "price": 0,
        "ticketType": "DD0",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETO2",
        "price": 0,
        "ticketType": "OOO",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETO2",
        "price": 0,
        "ticketType": "SOB",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETO2",
        "price": 112,
        "ticketType": "STD",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETO2",
        "price": 112,
        "ticketType": "STD",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETO2",
        "price": 112,
        "ticketType": "STD",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETO2",
        "price": 112,
        "ticketType": "VCN",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETO2",
        "price": 112,
        "ticketType": "VCN",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETO2",
        "price": 112,
        "ticketType": "VCN",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETPR",
        "price": 30,
        "ticketType": "BST",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETPR",
        "price": 30,
        "ticketType": "BST",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETPR",
        "price": 30,
        "ticketType": "BST",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETPR",
        "price": 0,
        "ticketType": "DD0",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETPR",
        "price": 0,
        "ticketType": "OOO",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETPR",
        "price": 0,
        "ticketType": "SOB",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETPR",
        "price": 142,
        "ticketType": "STD",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETPR",
        "price": 142,
        "ticketType": "STD",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETPR",
        "price": 142,
        "ticketType": "STD",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETPR",
        "price": 142,
        "ticketType": "VCN",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETPR",
        "price": 142,
        "ticketType": "VCN",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPETPR",
        "price": 142,
        "ticketType": "VCN",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPREM",
        "price": 30,
        "ticketType": "BST",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPREM",
        "price": 30,
        "ticketType": "BST",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPREM",
        "price": 30,
        "ticketType": "BST",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPREM",
        "price": 0,
        "ticketType": "DD0",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPREM",
        "price": 0,
        "ticketType": "OOO",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPREM",
        "price": 0,
        "ticketType": "SOB",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPREM",
        "price": 142,
        "ticketType": "STD",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPREM",
        "price": 142,
        "ticketType": "STD",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPREM",
        "price": 142,
        "ticketType": "STD",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPREM",
        "price": 142,
        "ticketType": "VCN",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPREM",
        "price": 142,
        "ticketType": "VCN",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NPREM",
        "price": 142,
        "ticketType": "VCN",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NRSEAT",
        "price": 0,
        "ticketType": "BST",
        "type": "A",
        "available": true,
        "yieldClass": "A",
        "capacity": 48,
        "intervalValue": 0,
        "resourceType": 3
    }, {
        "resourceCode": "NRSEAT",
        "price": 0,
        "ticketType": "DD0",
        "type": "A",
        "available": true,
        "yieldClass": "A",
        "capacity": 48,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "NRSEAT",
        "price": 0,
        "ticketType": "OOO",
        "type": "A",
        "available": true,
        "yieldClass": "A",
        "capacity": 48,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "NRSEAT",
        "price": 3.5,
        "ticketType": "STD",
        "type": "A",
        "available": true,
        "yieldClass": "A",
        "capacity": 48,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "NRSEAT",
        "price": 3.5,
        "ticketType": "STD",
        "type": "C",
        "available": true,
        "yieldClass": "A",
        "capacity": 48,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "NRSEAT",
        "price": 3.5,
        "ticketType": "STD",
        "type": "I",
        "available": true,
        "yieldClass": "A",
        "capacity": 48,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD",
        "price": 0,
        "ticketType": "BST",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD",
        "price": 0,
        "ticketType": "BST",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD",
        "price": 0,
        "ticketType": "BST",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD",
        "price": 0,
        "ticketType": "DD0",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD",
        "price": 0,
        "ticketType": "OOO",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD",
        "price": 0,
        "ticketType": "SOB",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD",
        "price": 18,
        "ticketType": "STD",
        "type": "A",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD",
        "price": 18,
        "ticketType": "STD",
        "type": "C",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD",
        "price": 18,
        "ticketType": "STD",
        "type": "I",
        "available": false,
        "yieldClass": "A",
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD2",
        "price": 0,
        "ticketType": "BST",
        "type": "A",
        "available": true,
        "yieldClass": "A",
        "capacity": 20,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD2",
        "price": 0,
        "ticketType": "BST",
        "type": "C",
        "available": true,
        "yieldClass": "A",
        "capacity": 20,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD2",
        "price": 0,
        "ticketType": "BST",
        "type": "I",
        "available": true,
        "yieldClass": "A",
        "capacity": 20,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD2",
        "price": 0,
        "ticketType": "DD0",
        "type": "A",
        "available": true,
        "yieldClass": "A",
        "capacity": 20,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD2",
        "price": 0,
        "ticketType": "OOO",
        "type": "A",
        "available": true,
        "yieldClass": "A",
        "capacity": 20,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD2",
        "price": 0,
        "ticketType": "SOB",
        "type": "A",
        "available": true,
        "yieldClass": "A",
        "capacity": 20,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD2",
        "price": 18,
        "ticketType": "STD",
        "type": "A",
        "available": true,
        "yieldClass": "A",
        "capacity": 20,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD2",
        "price": 18,
        "ticketType": "STD",
        "type": "C",
        "available": true,
        "yieldClass": "A",
        "capacity": 20,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD2",
        "price": 18,
        "ticketType": "STD",
        "type": "I",
        "available": true,
        "yieldClass": "A",
        "capacity": 20,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD3",
        "price": 0,
        "ticketType": "BST",
        "type": "A",
        "available": true,
        "yieldClass": "A",
        "capacity": 29,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD3",
        "price": 0,
        "ticketType": "BST",
        "type": "C",
        "available": true,
        "yieldClass": "A",
        "capacity": 29,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD3",
        "price": 0,
        "ticketType": "BST",
        "type": "I",
        "available": true,
        "yieldClass": "A",
        "capacity": 29,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD3",
        "price": 0,
        "ticketType": "DD0",
        "type": "A",
        "available": true,
        "yieldClass": "A",
        "capacity": 29,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD3",
        "price": 0,
        "ticketType": "OOO",
        "type": "A",
        "available": true,
        "yieldClass": "A",
        "capacity": 29,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD3",
        "price": 0,
        "ticketType": "SOB",
        "type": "A",
        "available": true,
        "yieldClass": "A",
        "capacity": 29,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD3",
        "price": 18,
        "ticketType": "STD",
        "type": "A",
        "available": true,
        "yieldClass": "A",
        "capacity": 29,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD3",
        "price": 18,
        "ticketType": "STD",
        "type": "C",
        "available": true,
        "yieldClass": "A",
        "capacity": 29,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "POD3",
        "price": 18,
        "ticketType": "STD",
        "type": "I",
        "available": true,
        "yieldClass": "A",
        "capacity": 29,
        "intervalValue": 0,
        "resourceType": null
    }, {
        "resourceCode": "CAR",
        "price": 0,
        "ticketType": null,
        "type": null,
        "available": true,
        "yieldClass": null,
        "capacity": 0,
        "intervalValue": 0,
        "resourceType": 2
    }],
}

// loop over myData.prices and sum capacity where available is true
var totalCapacity = 0;
for (var i = 0; i < myData.prices.length; i++) {
    if (myData.prices[i].available) {
        totalCapacity += Number(myData.prices[i].capacity);
    }
}

// output totalCapacity
console.log(totalCapacity);